title: They Might Be Ghosts!
email: theymightbeghosts@googlegroups.com
description: >-
  Improvisors celebrating life, here and in the hereafter
baseurl: ""
url: "https://theymightbeghosts.com"
author:
  name: "They Might Be Ghosts"

# Build settings
theme: minima

sass:
  quiet_deps: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
